project_name: flb-pubsub
before:
  hooks:
    - go mod tidy
builds:
  - id: "flb_pubsub"
    main: "."
    binary: flb_pubsub
    tags:
      - release
    flags: -buildmode=c-shared
    env:
      - GO_VERSION="1.18"
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc

  - id: "flb_pubsub_dll"
    main: "."
    binary: flb_pubsub
    tags:
      - release
    flags: -buildmode=c-shared
    env:
      - GO_VERSION="1.18"
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc-win32
    goos:
      - windows
    goarch:
      - amd64
      - 386
    overrides:
      - goos: windows
        goarch: 386
        env:
          - CC=i686-w64-mingw32-gcc-win32
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: gz
    files:
      - none*
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}{{ if not (eq .Os "Windows") }}.so{{else}}.dll{{end}}'
checksum:
  name_template: 'checksums.txt'
release:
changelog:
  skip: false
