project_name: flb-pubsub
dist: ./dist-darwin
before:
  hooks:
    - go mod tidy
builds:
  - id: "flb_pubsub"
    main: "."
    binary: flb_pubsub
    tags:
      - release
    flags: -buildmode=c-shared
    env:
      - GO_VERSION="1.18"
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
    format: binary
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}{{ if not (eq .Os "Windows") }}.so{{else}}.dll{{end}}'
   
checksum:
  name_template: 'checksums.txt'
